# Generated by Django 2.1.7 on 2019-03-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0002_auto_20190320_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('username',)},
        ),
        migrations.AddField(
            model_name='notification',
            name='tweets',
            field=models.ManyToManyField(to='twitterCloneApp.Tweet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='twitter_users',
            field=models.ManyToManyField(to='twitterCloneApp.TwitterUser'),
        ),
    ]
