# Generated by Django 2.1.7 on 2019-03-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0003_auto_20190320_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('title',)},
        ),
    ]
