# Generated by Django 2.1.7 on 2019-03-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0004_auto_20190320_0221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('author',)},
        ),
        migrations.RenameField(
            model_name='tweet',
            old_name='username',
            new_name='author',
        ),
    ]
