# Generated by Django 2.1.7 on 2019-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0005_auto_20190320_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.CharField(default='No message.', max_length=140),
        ),
    ]
