# Generated by Django 2.1.7 on 2019-03-22 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0006_auto_20190321_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ('tweetTime',)},
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweetTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='follows',
            field=models.ManyToManyField(related_name='followed_by', to='twitterCloneApp.TwitterUser'),
        ),
    ]
