# Generated by Django 2.1.7 on 2019-03-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0007_auto_20190322_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweetTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
