# Generated by Django 2.1.7 on 2019-03-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0009_auto_20190322_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tweets',
        ),
        migrations.AddField(
            model_name='notification',
            name='tweets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterCloneApp.Tweet'),
        ),
    ]
