# Generated by Django 2.1.7 on 2019-03-27 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0010_auto_20190327_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='tweets',
            new_name='tweet',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='twitter_users',
        ),
        migrations.AddField(
            model_name='notification',
            name='twitter_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='twitterCloneApp.TwitterUser'),
        ),
    ]
