# Generated by Django 2.1.7 on 2019-04-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0011_auto_20190327_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='Followers', to='twitterCloneApp.TwitterUser'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='twitterCloneApp.TwitterUser'),
        ),
    ]
