# Generated by Django 2.1.7 on 2019-04-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0012_auto_20190405_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='followers',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='twitterCloneApp.TwitterUser'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='following', to='twitterCloneApp.TwitterUser'),
        ),
    ]
