# Generated by Django 2.1.7 on 2019-04-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0013_auto_20190407_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='follow',
        ),
    ]
